### ISSUE TITLE
[Entity] Hashtag

### ISSUE THREAD

**Issue by kjh107704** [diginalog2019/diginalog#1]
**Is your feature request related to a problem? Please describe.**
해시태그 갈아엎어야 할 듯 하옵나이다

**Describe the solution you'd like**
저도 솔루션은 모르겠어요

**Describe alternatives you've considered**
대안? 없어요 해시태그는 해야함

**Additional context**

**Comment by siraegi** [comment]
해시태그를 왜 갈아엎어야 하나요? 괜찮을 것 같은데..ㅎㅎ

**Comment by kjh107704** [comment]
> 해시태그를 왜 갈아엎어야 하나요? 괜찮을 것 같은데..ㅎㅎ

사실 갈아엎는 표현보다는 시작을 해야 할 듯 하옵나이다..

**Comment by siraegi** [comment]
> > 해시태그를 왜 갈아엎어야 하나요? 괜찮을 것 같은데..ㅎㅎ
> 
> 사실 갈아엎는 표현보다는 시작을 해야 할 듯 하옵나이다..

Oh my god(...

**Comment by siraegi** [comment]
이거 왜이렇게 어렵나요

**Comment by kjh107704** [comment]
> 이거 왜이렇게 어렵나요

왜 자꾸 close 해버리시는거죠 선생님
