### ISSUE TITLE
[IMG] DB schema should be edited!

### ISSUE THREAD

**Issue by siraegi** [diginalog2019/diginalog#3]
**Is your feature request related to a problem? Please describe.**
DB에 이미지 올리는 스키마를 수정해야 합니다.
**Describe the solution you'd like**

**Describe alternatives you've considered**
DB에 파일 개수를 넣지 말고 Category에 products 배열 딸린 것처럼 넣기?
**Additional context**

**Comment by kjh107704** [comment]
file table 따로 만들어서 product와 연결해서 해결함.
